# Generated by Django 3.0.4 on 2020-03-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200306_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
